from setuptools import setup, find_packages
setup(
    name='script_processor',
    version='0.1.0',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'Click',
        'tqdm',
        'requests',
        'bs4',
        'cerberus',
        'markovify'
    ],
    entry_points='''
        [console_scripts]
        script_processor=script_processor:main
    ''',
)